---
title: "check fake CAMs"
author: "Julius Fenn, Nina Frings"
format:
  html:
    toc: true
    toc-depth: 3
    html-math-method: katex
---

# load drawn CAMs

Load R packages, drawn CAMs:

```{r}
#| label: load packages, functions
#| echo: true
#| warning: false

# sets the directory of location of this script as the current directory
# setwd(dirname(rstudioapi::getSourceEditorContext()$path))

### load packages
require(pacman)
p_load('igraph')


### load drawn CAM data
## t1
CAMdrawn_t1 <- readRDS(file = "CAMdrawn_t1.rds")
CAMdrawn_t1_fake <- readRDS(file = "CAMdrawn_t1_fake.rds")

## t2
CAMdrawn_t2 <- readRDS(file = "CAMdrawn_t2.rds")
CAMdrawn_t2_fake <- readRDS(file = "CAMdrawn_t2_fake.rds")

## t2 control group
CAMdrawn_t2_controlGroup <- readRDS(file = "CAMdrawn_t2_controlGroup.rds")
CAMdrawn_t2_controlGroup_fake <- readRDS(file = "CAMdrawn_t2_controlGroup_fake.rds")
```


# drawn fake CAMs

## t1

```{r}
#| label: draw t1
#| echo: true
#| warning: false

for(i in 1:length(CAMdrawn_t1_fake$ID_fakeCAMs)){
  print(CAMdrawn_t1_fake$ID_fakeCAMs[i])
  plot(CAMdrawn_t1[[CAMdrawn_t1_fake$ID_fakeCAMs[i]]], edge.arrow.size = .5,
     layout=layout_nicely, vertex.frame.color="black", asp = .5, margin = -0.1,
     vertex.size = 5, vertex.label.cex = .9)
}
```


## t2

```{r}
#| label: draw t2
#| echo: true
#| warning: false

for(i in 1:length(CAMdrawn_t2_fake$ID_fakeCAMs)){
  print(CAMdrawn_t2_fake$ID_fakeCAMs[i])
  plot(CAMdrawn_t2[[CAMdrawn_t2_fake$ID_fakeCAMs[i]]], edge.arrow.size = .5,
     layout=layout_nicely, vertex.frame.color="black", asp = .5, margin = -0.1,
     vertex.size = 5, vertex.label.cex = .9)
}
```

## t2 control group

```{r}
#| label: draw t2 control group
#| echo: true
#| warning: false

for(i in 1:length(CAMdrawn_t2_controlGroup_fake$ID_fakeCAMs)){
  print(CAMdrawn_t2_controlGroup_fake$ID_fakeCAMs[i])
  plot(CAMdrawn_t2_controlGroup[[CAMdrawn_t2_controlGroup_fake$ID_fakeCAMs[i]]], edge.arrow.size = .5,
     layout=layout_nicely, vertex.frame.color="black", asp = .5, margin = -0.1,
     vertex.size = 5, vertex.label.cex = .9)
}
```


